services:
  # VOICEVOX エンジン
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    networks:
      - app-network

  # FastAPI アプリケーション
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - VOICEVOX_URL=http://voicevox:50021
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./slides:/app/slides
      - ./audio:/app/audio
      - ./data:/app/data
      - ./api:/app/api
      - ./src:/app/src
      - ./.env:/app/.env
      - ./.env.example:/app/.env.example
    depends_on:
      - voicevox
    networks:
      - app-network
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

  # Svelte フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://api:8000
      - ORIGIN=http://localhost:3000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge